name: Production Build

on:
  push:
    branches:
      - Production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Write local.properties
        run: echo MAPS_API_KEY=${{ secrets.MAPS_API_KEY }} > ./local.properties

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew build
